[[themes]]
name = "Catppuccin"
[themes.palette]
background = "#24273a"
foreground = "#cad3f5"
black = "#24273a"
blue = "#8aadf4"
cyan = "#91d7e3"
green = "#a6da95"
magenta = "#c6a0f6"
red = "#ed8796"
white = "#cad3f5"
yellow = "#eed49f"
bright_black = "#24273a"
bright_blue = "#8aadf4"
bright_cyan = "#91d7e3"
bright_green = "#a6da95"
bright_magenta = "#c6a0f6"
bright_red = "#ed8796"
bright_white = "#cad3f5"
bright_yellow = "#eed49f"

[themes.component_style]
selection = { bg = "#363a4f", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#363a4f", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#a5adcb" }
