[[profile]]
name = "home"

[[profile.output]]
search = ["m=CF791", "s=HTJM400009", "v=Samsung Electric Company"]
enable = true
mode = "3440x1440@100Hz"
position = "0,0"
scale = 1.25
transform = "normal"

[[profile.output]]
search = ["m=0x0000", "s=0x01010101", "v=Invalid Vendor Codename - RTK"]
enable = true
mode = "2560x1600@144Hz"
transform = "normal"
position = "600,1152"
scale = 1.666667


[[profile]]
name = "remote"

[[profile.output]]
search = ["m=0x0000", "s=0x01010101", "v=Invalid Vendor Codename - RTK"]
enable = true
mode = "2560x1600@144Hz"
transform = "normal"
position = "0,0"
scale = 1.666667
