alias ls="lsd"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias lt="ls --tree"
alias cat="bat"
alias grep="rg"
alias du="dust"
alias icat="kitty +kitten icat"
alias k8s_project_dev="gcloud config set project topcv-vn-dev && gcloud container clusters get-credentials dev-01 --zone asia-southeast1-c"
alias k8s_project_dp="gcloud config set project dataplatform-296603 && gcloud container clusters get-credentials prod-01 --region asia-southeast1"
alias k="kubectl"
alias ssh="TERM=xterm-256color ssh"
alias gi="git-ignore"
alias lzg="lazygit"
alias lzd="lazydocker"
