[tools]
gcloud = "latest"
helm = "latest"
node = "latest"
kubectl = "latest"
pre-commit = "latest"
terraform = "latest"
awscli = "latest"
uv = "latest"
python = "system"
fzf = "latest"
deno = "latest"
lazygit = "latest"
pnpm = "latest"
bun = "latest"
